### ISSUE TITLE
Unstable features cannot be used with Rust beta

### ISSUE THREAD

**Issue by Ape** [wackywendell/sorting-rs#1]
Rust beta and any stable release in the future cannot use unstable features. Building this on beta2 fails with this message:

```
src/lib.rs:31:1: 31:37 error: unstable feature
src/lib.rs:31 #![feature(step_by, slice_patterns)]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
```

Any unstable features should be replaced with stable ones or external cargo libraries.

**Comment by wackywendell** [comment]
Yes, I've been meaning to do this for a while... thanks for giving me the push!

Fixed with 055847961f618f9ee986749a0b70f985ad463001.
